### ISSUE TITLE
Reconstructed Spectrum has negative values

### ISSUE THREAD

**Issue by adhusch** [guevaracodina/vancouver#1]
Hi,

first thanks for the nice contribution :)

Could you comment on the fact that the reconstructed Raman spectra contain negative values with your implementation? (Even in you example PNG). In the original paper by Zhao et al. this is not discussed at all (and i first though that their polynomial constitutes a lower bound on the spectrum and thus yields a strictly positive reconstruction) but it seems by construction the algorithm will always produce some negative outputs. 

Best
Andy

**Comment by guevaracodina** [comment]
Hi Andy,

Thank you for the observation. That was something that did not bother me
much, since spectra are often normalized in some way (min-max, auc, etc.)
Therefore I end up with non-negative values for my application.

Best

Edgar

**Comment by guevaracodina** [comment]
Dear @adhusch 

A small correction was implemented to avoid negative data points in the Raman spectra.
[https://github.com/guevaracodina/vancouver/blob/master/vancouver.m](url)

Thanks for noticing

Edgar
